ko:
  languageName: 한국어
  title: 주경야근
  weight: 1
  
en:
  languageName: English
  title: Working around the clock
  params:
    description: Personal blog about tech
  weight: 2

zh-hans:
  languageName: 简体中文
  weight: 100
