# see https://hugomods.com/en/docs/google-analytics/.
# Google Analytics, please make sure you've imported the Google Analytics module.
googleAnalytics: 'G-CD1265EM87' 

# disqusShortname: XXXXXX # The Disqus shortname.
